### ISSUE TITLE
A potential bug

### ISSUE THREAD

**Issue by notesofdabbler** [dirkschumacher/ompr.highs#1] opened 2022-09-10 00:19 UTC
Thanks for the nice`ompr` package and quickly providing a connect to `highs` package. I was trying a transportation example and it seems like the solution is not optimal. If I try to manually take information from `ompr` model and pass to `highs` solver, then it gives the optimal solution. I have the details of what I tried in this [location](https://notesofdabbler.github.io/optwithR/gms_trnsprt_ompr_check.html). I am not sure if I am doing something incorrect in using `ompr` directly with `highs`

**Comment by dirkschumacher** [comment] 2022-09-10 05:06
Great thanks. Will look into it.

**Comment by dirkschumacher** [comment] 2022-09-10 05:30
I think the problem is that {ompr} maximises the objective by default (historical reasons) and {highs} minimises it.

Try adding `set_objective(sum_over(cost(i, j) * x[i, j], i = 1:np, j = 1:nm), sense = "min")` and see what happens.

**Comment by notesofdabbler** [comment] 2022-09-11 03:42
Thanks for clarifying. Once I specified the objective to minimize, the example solved correctly.

**Comment by dirkschumacher** [comment] 2022-09-11 05:05
Cool. Really appreciate the time you took to describe the problem and report it.

**Comment by notesofdabbler** [comment] 2022-09-11 16:50
Sorry to reopen the issue. When I try the example in highs package, everything works fine but the reported objective does not include the offset parameter. The objective is `x0+x1+3` with optimal solution `x0=0.5, x1=2.25` and objective value of 5.75 but the objective value reported from solution is 2.75. Just wanted to check if it is by design that offset is not reported (since it doesn't impact the optimization). Here is the [full code](https://notesofdabbler.github.io/optwithR/highs_example_ompr.html)

**Comment by dirkschumacher** [comment] 2022-09-12 04:47
Should be fixed now. Thanks!

**Closed as completed** 2022-09-12 04:47 UTC
